### ISSUE TITLE
where to find the data?

### ISSUE THREAD

**Issue by liamxg** [cambiotraining/sars-cov-2-genomics#27]

**Comment by tavareshugo** [comment]
Thanks for the question.

It's in the "Setup" page, here: https://cambiotraining.github.io/sars-cov-2-genomics/101-setup.html#Data

I will leave the issue open, to make it more visible in the future.

**Comment by LiXingguangBrandonStark** [comment]
thanks. I Iike this tutorial.

**Comment by tavareshugo** [comment]
We are currently working on a new Phylogenetics course, which we hope to run next year in Cambridge. If you would like to keep updated on this, please [sign-up for our monthly newsletter](https://lists.cam.ac.uk/sympa/subscribe/ucam-bioinfo-training) and you will be able to see when we run the course again.

**Comment by tavareshugo** [comment]
Like I said, we are still developing this at the moment, so I don't have anything more detailed yet, sorry. There is however good [documentation on IQTree2](http://www.iqtree.org/doc/) website (for maximum-likelihood methods) and [BEAST](https://taming-the-beast.org/tutorials/) (for bayesian methods).
