### ISSUE TITLE
Timetable issue: lengthening software management session time allocation

### ISSUE THREAD

**Issue by bsalehe** [cambiotraining/sars-cov-2-genomics#46]
The time allocated for software management was not enough (1hr) and participants requested more time particularly for WSL2. So in the last day hopefully we could have something like below:

- 30 minutes just for overview of software management in bioinformatics
- 90 minutes for WSL2
- 30 minutes for demo VM
- 30 minutes probably for demo configuring nextflow in the HPC to run viralrecon.

**Comment by tavareshugo** [comment]
Closed with https://github.com/cambiotraining/sars-cov-2-genomics/commit/3fe3ca84c48b598f8185c8b8aacbda103a0ce943
