### ISSUE TITLE
Test Guacamole for SARS workshop 5th Feb

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/sars-cov-2-genomics#52]
Start with testing the two case studies ([Switzerland](https://cambiotraining.github.io/sars-cov-2-genomics/materials/03-case_studies/01-switzerland.html) and [South Africa](https://cambiotraining.github.io/sars-cov-2-genomics/materials/03-case_studies/02-southafrica.html)) to make sure both pipelines work. 

- [x] viralrecon with `--platform illumina`
- [x] viralrecon with `--platform nanopore`
- [x] seqkit
- [x] pangolin 
- [x] nextclade
- [x] phylogeny
- [x] civet
- [x] integration and visualisation with R

**Comment by bsalehe** [comment]
When running pangolin for nanopore (Switzerland dataset) I get this weird error `AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?`. It could be that the `sars` environment for downstream analysis some packages like pangolion have broken dependencies.

- Possible fix for diagnosis for this error is to install pangolin in the separate environment and see if it runs fine or the same error will come up.

**Comment by bsalehe** [comment]
Another interesting thing is that seqkit works well in the new `sars` env as opposed to the reported issue #35 at least for the nanopore dataset.

**Comment by bsalehe** [comment]
I am also getting the following error when I am running civet on the Switzerland case study (Nanopore). This also may need fixing.

```
TabErrorin line 262 of <string>:
inconsistent use of tabs and spaces in indentation (<string>, line 262)
  File "/home/ubuntu/miniforge3/envs/sars/lib/python3.12/tokenize.py", line 541, in _generate_tokens_from_c_tokenizer
  File "/home/ubuntu/miniforge3/envs/sars/lib/python3.12/tokenize.py", line 537, in _generate_tokens_from_c_tokenizer
```

**Comment by bsalehe** [comment]
The R packages required for running script `07-data_integration.R` all loaded well except `janitor` which is not yet installed. I get this error `Error in library(janitor) : there is no package called ‘janitor’` when I load it.

**Comment by bsalehe** [comment]
I have finished testing. So additional thing to fix apart from pangolin and civet is installing package janitor.

Cheers!
-

**Comment by tavareshugo** [comment]
Due to package conflicts, instead of having one single environment, we will split into individual environments: 

```bash
mamba create -n nextflow nextflow
mamba create -n seqkit seqkit
mamba create -n pangolin pangolin
mamba create -n phylo mafft iqtree treetime figtree
```

**Comment by bsalehe** [comment]
Installing pangolin, and civet in separate environments appears to be not causing any issue and both ran fine. So maybe would be worth doing that for the sake of upcoming training.

**Comment by tavareshugo** [comment]
`viralrecon` version on the current images is not the latest - need to update

**Comment by bsalehe** [comment]
I think we might need to split the `04-lineages.sh` into two scripts, one for running nextclade and the other one for running pangolin as we have separate environments for pangolin and nextclade. This might remove the need to go back and forth when assigning the lineages.

**Comment by tavareshugo** [comment]
@liamxg thank you for your question. 
you can find that information on [this section](https://cambiotraining.github.io/sars-cov-2-genomics/materials/05-software/03-software_setup.html).
