### ISSUE TITLE
get ground truth mutations for EQA panels '23' version

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/sars-cov-2-genomics#54]
For the new panels named UKNEQAS_230[1-6] we need to have the list of expected mutations to assess sensitivity and precision of the analysis. For the EQA exercise using the script `scripts/09-eqa_validation.R`. 

- [x] Run viralrecon on the new samples sent by UKHSA (currently named `eqa23_ukhsa`
- [x] Extract high-quality mutations from the file `variants/ivar/variants_long_table.csv`. The table should be filtered for AF >= 0.75 and DP >= 10. Save this as a file named `eqa23_mutations.csv`.
- [x] Copy the `resources` folder from another `eqa_illumina` directory to the `eqa_ukhsa` folder. 
- [x] Add the `eqa23_mutations.csv` to `resources/eqa_validation` folder.
- [x] Test the R script `09-eqa_validation.R` with the new file (exercise in section 10.7).
- [x] Upload to dropbox: `scripts`, `resources` and `sample_info.csv`

The file format should be similar to this (from the previous '22' panels):

```
sample,pos,ref,expected_alt
UKNEQAS2201,913,C,T
UKNEQAS2201,3037,C,T
UKNEQAS2201,3267,C,T
UKNEQAS2201,4999,C,T
UKNEQAS2201,5388,C,A
UKNEQAS2201,5986,C,T
UKNEQAS2201,6633,C,T
UKNEQAS2201,6954,T,C
UKNEQAS2201,14408,C,T
```

**Comment by bsalehe** [comment]
> The filtering condition seems to be too stringent, I get only two mutations. Can we relax a condition little bit further down perhaps with AF>=50 or 60 and increase DP???

I think it is OK with the same condition. It was giving only two rows for some reasons.

**Comment by tavareshugo** [comment]
We should not change those thresholds, because I think those are the thresholds used by `viralrecon` to include mutations in the final consensus FASTA. See [here](https://github.com/nf-core/viralrecon/blob/3731dd3a32a67a2648ea22c2bd980c224abdaee2/conf/modules_illumina.config#L407).
